version: '3'
services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      - api-04
  api-04:
     image: kitskat/marcifx:v7.5
     command: flask run --host=0.0.0.0 --port=5000
     ports:
        - 5005:5000
     environment:
        - FLASK_APP=app.py
     depends_on:
        - cache-server

  cache-server:  
      image: redis
      command: redis-server --appendonly yes